export const START_CHAT = 'START_CHAT';
export const SEND_MSG_TO_CHAT_ROOM = 'SEND_MSG_TO_CHAT_ROOM';
export const GET_CHATS = 'GET_CHATS';
export const GET_CHAT_DETAILS = 'GET_CHAT_DETAILS';
export const SELECTED_CHAT = 'SELECTED_CHAT';
