export const ADD_RATING = 'ADD_RATING';
export const GET_RATING = 'GET_RATING';
export const ADD_ORGANISATION = 'ADD_ORGANISATION';
export const SEARCH_ORGANISATION = 'SEARCH_ORGANISATION';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_LEARNER_PROFILE = 'UPDATE_LEARNER_PROFILE';

export const REMOVE_SUBJECT = 'REMOVE_SUBJECT';
export const ADD_SERVICES = 'ADD_SERVICES';

export const GET_USER_FAQS = 'GET_USER_FAQS';
export const GET_TUTOR_FAQS = 'GET_TUTOR_FAQS';
export const GET_FORGOT_PASS = 'GET_FORGOT_PASS';
export const GET_FORGOT_CHANGE_PASS = 'GET_FORGOT_CHANGE_PASS';