export const GET_WORKSHOPS = 'GET_WORKSHOPS';
export const GET_WORKSHOP_BY_ID = 'GET_WORKSHOP_BY_ID';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const GET_SUBSCRIBED_WORKSHOPS = 'GET_SUBSCRIBED_WORKSHOPS';
export const SELECTED_WORKSHOP = 'SELECTED_WORKSHOP';

export const WORKSHOP_REGISTRATION = 'WORKSHOP_REGISTRATION';
export const SEARCH_WORKSHOP = 'SEARCH_WORKSHOP';
