export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const GET_BANNERS = 'GET_BANNERS';
export const GET_AVATAR = 'GET_AVATAR';
export const GET_ID_PROOF = 'GET_ID_PROOF';
export const GET_WORK_PROOF = 'GET_WORK_PROOF';
export const GET_AWARD_PROOF = 'GET_AWARD_PROOF';
export const GET_HIGHEST_PROOF = 'GET_HIGHEST_PROOF';
export const GET_DEGREE_PROOF = 'GET_DEGREE_PROOF';
export const GET_FIRM_PROOF = 'GET_FIRM_PROOF';
export const GET_HEAD_PROOF = 'GET_HEAD_PROOF';
export const GET_BACKDROP = 'GET_BACKDROP';
export const GET_LOGO = 'GET_LOGO';
export const GET_REFERRAL_CODE = 'GET_REFERRAL_CODE';
export const GET_DISTANCE_BETWEEN_TWO = 'GET_DISTANCE_BETWEEN_TWO';
export const GET_COMPETITION_DOCUMENTS = 'GET_COMPETITION_DOCUMENTS';
export const GET_GALLERY = 'GET_GALLERY';

export const RESET_UPLOADED_FILES = 'RESET_UPLOADED_FILES';
