export const GET_COMPETITION = 'GET_COMPETITION';
export const GET_COMPETITION_BY_ID = 'GET_COMPETITION_BY_ID';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const GET_SUBSCRIBED_COMPETITIONS = 'GET_SUBSCRIBED_COMPETITIONS';

export const SELECTED_COMPETITION = 'SELECTED_COMPETITION ';

export const COMPETITION_REGISTRATION = 'COMPETITION_REGISTRATION ';
export const COMPETITION_UPLOADS = 'COMPETITION_UPLOADS';
