export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILL_BY_ID = 'GET_SKILL_BY_ID';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const GET_SUBSCRIBED_SKILLS = 'GET_SUBSCRIBED_SKILLS';
export const SELECTED_SKILL = 'SELECTED_SKILL';
export const SKILL_REGISTRATION = 'SKILL_REGISTRATION';
export const BOOK_A_DEMO = 'BOOK_A_DEMO';
export const SEARCH_SKILL = 'SEARCH_SKILL';
