export const FETCH_SEGMENTS = 'FETCH_SEGMENTS';
export const FETCH_LEVELS = 'FETCH_LEVELS';
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const SUBJECT_MESSAGE = 'SUBJECT_MESSAGE';

export const SELECT_SEGMENT = 'SELECT_SEGMENT';
export const SELECT_LEVEL = 'SELECT_LEVEL';
export const SELECT_STREAM = 'SELECT_STREAM';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const SEARCH_LEVEL = 'SEARCH_LEVEL';
export const SEARCH_STREAM = 'SEARCH_STREAM';
export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';
export const SEARCH_SUBJECTS = 'SEARCH_SUBJECTS';
